---
title: "Linear Mixed Models (LME) Workshop"
---

::: {.callout-note}
### Kuis _Pre-test_
`lme` merupakan teknik statistik yang kompleks dan menguasainya perlu melewati _learning curve_ yang lumayan curam. Agar _workshop_ ini bermanfaat, peserta ***wajib*** untuk mengikuti kuis _pre-test_ sebelum _workshop_ untuk mengetahui apa saja materi yang perlu dipersiapkan sebelum _workshop_ dimulai.

Silakan klik _navigation bar_ `Kuis _Pre-test_`untuk mengikuti kuis. 
:::

::: {.callout-warning}
#### Perhatian
Materi akan terus diperbarui sampai dengan H-1 _workshop_.
:::

Laman web berikut ini merupakan laman web untuk **Workshop Linear Mixed Models** yang diselenggarakan oleh program studi Doktor (S3) Psikologi, Fakultas Psikologi, Universitas Airlangga.

Materi berlisensi [<i class="fab fa-creative-commons"><i class="fa fa-universal-access"></i></i> BY 4.0](https://creativecommons.org/licenses/by/4.0/). **Materi bebas digunakan kembali namun wajib mengatribusi sumber aslinya**.

## Waktu dan tempat

*Workshop* diselenggarakan pada hari **Sabtu, 9 Mei 2026** pukul 15.00 - 17.00 WIB secara virtual melalui Microsoft Teams.

::: {.callout-note}
**Catatan**: Peserta dapat _join meeting_ melalui _browser_, sehingga **tidak harus** _login_ atau memiliki akun MS Teams. 
Namun, apabila peserta ingin menyimpan atau mengakses _history chat_ setelah _workshop_ berakhir, peserta disarankan untuk _login_ akun Microsoft yang disediakan Universitas Airlangga (email dengan domain `@drive.unair.ac.id`) sebelum _join meeting_.
:::

:::{style="text-align: center;"}
[**Klik disini untuk _join meeting_**](https://teams.microsoft.com/meet/48621148240860?p=tnmFEem9q42zVoQqVO)
:::

## *Outline* materi

Materi yang tersedia di laman web ini juga mencakup konsep dasar *ordinary least square regression* selain pengenalan `lme`. 

Peserta juga akan diminta untuk menganalisis data dengan menggunakan `lme` dan melaporkannya dengan format yang biasa digunakan dalam artikel penelitian.

Berikut adalah *outline* materi yang tersedia di laman web ini:

### **Bagian 1️⃣**: _Ordinary Least Square Regression_  

* Berlatih menginspeksi data secara visual dengan _scatterplot_
* Model regresi linear (_ordinary least square_)
* Menarik garis regresi (_fitted regression line_)
* Varians yang dapat dan yang tidak dapat dijelaskan oleh model (_R_^2^)
* Menguji hipotesis
* Mengecek kecocokan model dengan data (_model fit_)
* Mengecek asumsi
  - Distribusi (normalitas) residual
  - Homoskedastisitas
  - Multikolinearitas
* Mendeteksi _outliers_
* Menguji _interaction effects_ dan _model change_
* Menulis hasil analisis regresi linear dengan _interaction terms_ dalam manuskrip

::: {.callout-important}
#### Regresi OLS tidak diajarkan di _workshop_
Karena asumsinya mahasiswa S3 sudah memiliki pengetahuan statistik dasar, maka  **Bagian 1 tidak diajarkan** di _workshop_. Bagian 1 **harus dikuasai** oleh peserta terlebih dahulu sebelum memulai _workshop_ dan dapat dipelajari secara mandiri.
:::

### **Bagian 2️⃣**: _Linear Mixed Effects Model_ 

* Struktur data berjenjang/bersarang (*hierarchical/nested data*)
* _Within-_ dan _between-group variances_
* Pengantar _linear mixed-effect_ (`lme`)
* _Intra-class correlation_ dan _likelihood ratio test_ (LRT)
* Membandingkan garis regresi antar kelompok dengan `lme`
* `lme` dengan prediktor level 1 (_random coefficients model_)
  - Mengidentifikasi _intercept_ (konstanta) yang berbeda antar kelompok (_random-intercept model_)
  - Mengidentifikasi _slopes_ (gradien/kemiringan garis) yang berbeda antar kelompok (_random slopes model_)
* "_Explained variances_" ([Nakagawa & Schielzeth, 2012](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210x.2012.00261.x))
  - _Marginal R_^2^
  - _Conditional R_^2^
* _Contextual effect_ dan _partitioning/centering_
* Melaporkan analisis dengan `lme` dalam manuskrip
* Pengukuran berulang (_repeated measures_) dan _experience sampling_

### **Bagian 3️⃣**: `lme` untuk Pengukuran Berulang dan *Experience Sampling*

* Keterbatasan `lme` biasa untuk data pengukuran berulang
* *Repeated measures* dengan `lme`
  - Struktur kovarians residual: *Identity*, *Compound Symmetry*, *Unstructured*
  - Membandingkan model dengan struktur residual berbeda
* *Experience Sampling Method* (ESM)
  - Apa itu ESM dan pada saat seperti apa ESM dilakukan?
  - *Temporal autocorrelation* dan struktur AR(1) & ARMA(1,1)
  - *Person-mean centering*: efek *within-* vs. *between-person*
  - *Cross-level interaction* dalam data ESM
* _Setup_ di jamovi GAMLj
* Melaporkan hasil dalam manuskrip

::: {.callout-important}
#### _Repeated Measures_ dan ESM tidak diajarkan
Karena keterbatasan waktu, bagian 3️⃣ **tidak diajarkan** secara mendalam di _workshop_. Materi tersedia di laman web ini dan dapat dipelajari peserta secara mandiri.
:::

::: {.callout-note}
#### Unduh materi dalam bentuk PDF** 
Klik _navigation bar_ yang mengarah pada PDF materi, kemudian tekan `ctrl` dan `p` bersamaan. Setelah _window_ untuk _print_ muncul, pilih `Save to PDF` dan klik `Save`.
:::

## Referensi

* Brown, V.A. (2021). An Introduction to Linear Mixed-Effects Modeling in R. _Advances in Methods and Practices in Psychological Science, 4_(1), 1-19. doi: [10.1177/2515245920960351](https://doi.org/10.1177/2515245920960351) 
* Galucci, M. (2025). GAMLj: General analysis for the linear model in jamovi. <https://gamlj.github.io/index.html>
* Galucci, M. (2025). Mixed models module. <https://gamlj.github.io/mixed.html>
* Hajduk, G.K. (2017). Introduction to linear mixed models. <https://ourcodingclub.github.io/2017/03/15/mixed-models.html>
* Nakagawa, S. and Schielzeth, H. (2013), A general and simple method for obtaining _R_^2^ from generalized linear mixed‐effects models. _Methods in Ecology and Evolution_, 4: 133-142. doi: [10.1111/j.2041-210x.2012.00261.x](https://doi.org/10.1111/j.2041-210x.2012.00261.x)
* Peugh, James L. (2010). A practical guide to multilevel modeling. Journal of School Psychology, 48, 85-112. doi: [10.1016/j.jsp.2009.09.002](https://doi.org/10.1016/j.jsp.2009.09.002)
* Winter, B. (2013). Linear models and linear mixed effects models in R with linguistic applications. [arXiv:1308.5499](https://web.stanford.edu/class/psych252/section/Mixed_models_tutorial.html).

## Referensi tambahan untuk _repeated measures_ dan _experience sampling_

* Bolger, N., & Laurenceau, J-P. (2013). *Intensive longitudinal methods: An introduction to diary and experience sampling research*. Guilford Press.
* Hamaker, E.L., Kuiper, R.M., & Grasman, R.P.P.P. (2015). A critique of the cross-lagged panel model. *Psychological Methods*, *20*(1), 102-116. doi: [10.1037/a0038889](https://doi.org/10.1037/a0038889)
* Nezlek, J.B. (2012). Multilevel modeling analyses of diary-style data. In M.R. Mehl & T.S. Conner (Eds.), *Handbook of Research Methods for Studying Daily Life* (pp. 384-410). Guilford Press.
* Trull, T.J. & Ebner-Priemer, U. (2014). The role of ambulatory assessment in psychological science. *Current Directions in Psychological Science*, *23*(6), 466-470. doi: [10.1177/0963721414550706](https://doi.org/10.1177/0963721414550706)

## Contoh penelitian dengan `lme`

* Youngseek, K. & Stanton, J.M. (2016). Institutional and individual factors affecting scientists' data-sharing behaviors: A multilevel analysis. Journal of the Association for Information Science and Technology, 67(4), 776-799. doi: [10.1002/asi.23424](https://asistdl.onlinelibrary.wiley.com/doi/abs/10.1002/asi.23424)
* Zein, R.A. & Gollwitzer, M. (2025). More Than Dilution: Religiosity and Conflict Perceptions Predict Perceived Utility of Religious, but not Scientific Explanations. PsyArXiv. doi: [10.31234/osf.io/4rjqs_v1](https://doi.org/10.31234/osf.io/4rjqs_v1)
* Zein, R.A., Putri, N.K., & Ridlo, I.A. (2019). Do Justice and Trust Affect Acceptability of Indonesian Social Health Insurance Policy? A cross-sectional survey of laypeople and health care workers.
_International Journal of Health Governance_, _25_(1), 78-92. doi: [10.1108/IJHG-05-2019-0028](https://doi.org/10.1108/IJHG-05-2019-0028)

## Sumber belajar lainnya

* [LEMMA (Learning Environment for Multilevel Methods and Applications)](https://www.cmm.bris.ac.uk/lemma/)
* [Learning Statistics with jamovi](https://sites.google.com/brookes.ac.uk/learning-stats-with-jamovi)
* [Video tutorial jamovi dari Datalab](https://datalab.cc/tools/jamovi)

## Sebelum mulai workshop

* Sebaiknya semua peserta sudah memasang jamovi pada perangkatnya masing-masing, untuk menghindari terlalu banyaknya waktu untuk menyelesaikan *troubleshooting* instalasi ketika *workshop*.
* Peserta sangat disarankan untuk menonton [video tutorial jamovi](https://datalab.cc/tools/jamovi) sebelum *workshop* untuk belajar menavigasikan menu dan fitur yang ada dalam jamovi. Cukup hanya dengan menonton bagian *Welcome*, *Installing jamovi*, dan *Navigating jamovi* (total durasi kurang lebih hanya 7 menit).

## Cara instalasi *module* GAMLj v.3

Mohon untuk menyimak video petunjuk instalasi *module* GAMLj jamovi berikut ini.

Gunakan **jamovi versi stabil yang terbaru** (2.6.44) [untuk Windows](https://www.jamovi.org/downloads/jamovi-2.6.44.0-win-x64.exe) atau [MacOS](https://www.jamovi.org/download.html).

{{< video https://www.youtube.com/watch?v=XWavBKgTEuU >}}

## Tutorial jamovi + _modules_

Saat ini, sudah cukup banyak tutorial jamovi yang tersedia. Salah satu yang paling populer dan komperhensif adalah tutorial di bawah ini ⬇️

{{< video https://youtu.be/t0tQcs-E5Z4?si=wur9Er_M92zR-J2v >}}

[Simak seluruh video tutorial di <i class="fa-brands fa-youtube"></i> _playlist_.](https://www.youtube.com/playlist?list=PLvYqRUmlLZUMJ0EUxuTAA1f407wmBQ1QX)

## Evaluasi _workshop_

Setelah _workshop_, peserta dimohon untuk mengisi kuesioner evaluasi yang dapat diakses di _menu bar_ `Survei` bagian pojok kanan atas sebagai bahan evaluasi untuk meningkatkan kualitas materi _workshop_ di masa depan.